### ISSUE TITLE
Removing a Spline Point from a Rank with No Spline Points Crashes

### ISSUE THREAD

**Issue by astory** [astory/RankPanda#15]
Steps to Reproduce:
Create a rank with no spline points.
Right click on arrow-end of rank (possibly multiple times)

Observed behavior:
Field display goes blank; traceback appears in terminal

Expected behavior:
Nothing should happen

Traceback (most recent call last):
  File "/home/alec/Compiled/RankPanda/RankPanda/GUIField.py", line 140, in OnPaint
    self.Draw()
  File "/home/alec/Compiled/RankPanda/RankPanda/GUIField.py", line 179, in Draw
    self.DrawRanks(self.fieldRect, self.main.core.GetRanks(), RANK_COLOUR, dc)
  File "/home/alec/Compiled/RankPanda/RankPanda/GUIField.py", line 547, in DrawRanks
    self.DrawLocation(rect, r[2], dc, colour, mini)
  File "/home/alec/Compiled/RankPanda/RankPanda/GUIField.py", line 571, in DrawLocation
    dc.DrawCircle(pts[1].x, pts[1].y, endpoint_radius)
IndexError: list index out of range

**Comment by astory** [comment]
This looks like it's happening because Rank.DeleteSplinePoint doesn't stop to check if it's removing one of the last two points - but those two points are required for drawing the rank.

**Comment by astory** [comment]
DeleteSplinePoint will now not delete either of the last two points.  Closed by e28f619fba97a31432c0ba116203dca1a8eced74
